### ISSUE TITLE
new gpg key for apt repo?

### ISSUE THREAD

**Issue by hdeadman** [spotify/puppet-puppetexplorer#12]
Is there a new key for the apt repo that puppetexplorer is deployed to? 

http://keyserver.ubuntu.com/pks/lookup?op=vindex&search=puppetexplorer&fingerprint=on

**Comment by daenney** [comment]
The packages are now being signed by the Spotify FOSS Board GPG key but unfortunately this one isn't available on `keyserver.ubuntu.com` for some reason right now. I'm looking into getting that fixed.

**Comment by dalen** [comment]
Sorry for the delay on this, I've been AFK for a while with a broken wrist. But I've uploaded it again now and it seems to be there. Not sure why it disappeared.
